// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: relay_peer.proto

#ifndef PROTOBUF_relay_5fpeer_2eproto__INCLUDED
#define PROTOBUF_relay_5fpeer_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3002000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3002000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
// @@protoc_insertion_point(includes)
namespace proto {
class PeerToRelay;
class PeerToRelayDefaultTypeInternal;
extern PeerToRelayDefaultTypeInternal _PeerToRelay_default_instance_;
}  // namespace proto

namespace proto {

namespace protobuf_relay_5fpeer_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_relay_5fpeer_2eproto

// ===================================================================

class PeerToRelay : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:proto.PeerToRelay) */ {
 public:
  PeerToRelay();
  virtual ~PeerToRelay();

  PeerToRelay(const PeerToRelay& from);

  inline PeerToRelay& operator=(const PeerToRelay& from) {
    CopyFrom(from);
    return *this;
  }

  static const PeerToRelay& default_instance();

  static inline const PeerToRelay* internal_default_instance() {
    return reinterpret_cast<const PeerToRelay*>(
               &_PeerToRelay_default_instance_);
  }

  void Swap(PeerToRelay* other);

  // implements Message ----------------------------------------------

  inline PeerToRelay* New() const PROTOBUF_FINAL { return New(NULL); }

  PeerToRelay* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from)
    PROTOBUF_FINAL;
  void CopyFrom(const PeerToRelay& from);
  void MergeFrom(const PeerToRelay& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  void DiscardUnknownFields();
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(PeerToRelay* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::std::string GetTypeName() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // bytes public_key = 2;
  void clear_public_key();
  static const int kPublicKeyFieldNumber = 2;
  const ::std::string& public_key() const;
  void set_public_key(const ::std::string& value);
  #if LANG_CXX11
  void set_public_key(::std::string&& value);
  #endif
  void set_public_key(const char* value);
  void set_public_key(const void* value, size_t size);
  ::std::string* mutable_public_key();
  ::std::string* release_public_key();
  void set_allocated_public_key(::std::string* public_key);

  // bytes data = 3;
  void clear_data();
  static const int kDataFieldNumber = 3;
  const ::std::string& data() const;
  void set_data(const ::std::string& value);
  #if LANG_CXX11
  void set_data(::std::string&& value);
  #endif
  void set_data(const char* value);
  void set_data(const void* value, size_t size);
  ::std::string* mutable_data();
  ::std::string* release_data();
  void set_allocated_data(::std::string* data);

  // uint32 key_id = 1;
  void clear_key_id();
  static const int kKeyIdFieldNumber = 1;
  ::google::protobuf::uint32 key_id() const;
  void set_key_id(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:proto.PeerToRelay)
 private:

  ::google::protobuf::internal::InternalMetadataWithArenaLite _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr public_key_;
  ::google::protobuf::internal::ArenaStringPtr data_;
  ::google::protobuf::uint32 key_id_;
  mutable int _cached_size_;
  friend struct  protobuf_relay_5fpeer_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// PeerToRelay

// uint32 key_id = 1;
inline void PeerToRelay::clear_key_id() {
  key_id_ = 0u;
}
inline ::google::protobuf::uint32 PeerToRelay::key_id() const {
  // @@protoc_insertion_point(field_get:proto.PeerToRelay.key_id)
  return key_id_;
}
inline void PeerToRelay::set_key_id(::google::protobuf::uint32 value) {
  
  key_id_ = value;
  // @@protoc_insertion_point(field_set:proto.PeerToRelay.key_id)
}

// bytes public_key = 2;
inline void PeerToRelay::clear_public_key() {
  public_key_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& PeerToRelay::public_key() const {
  // @@protoc_insertion_point(field_get:proto.PeerToRelay.public_key)
  return public_key_.GetNoArena();
}
inline void PeerToRelay::set_public_key(const ::std::string& value) {
  
  public_key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:proto.PeerToRelay.public_key)
}
#if LANG_CXX11
inline void PeerToRelay::set_public_key(::std::string&& value) {
  
  public_key_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:proto.PeerToRelay.public_key)
}
#endif
inline void PeerToRelay::set_public_key(const char* value) {
  
  public_key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:proto.PeerToRelay.public_key)
}
inline void PeerToRelay::set_public_key(const void* value, size_t size) {
  
  public_key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:proto.PeerToRelay.public_key)
}
inline ::std::string* PeerToRelay::mutable_public_key() {
  
  // @@protoc_insertion_point(field_mutable:proto.PeerToRelay.public_key)
  return public_key_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* PeerToRelay::release_public_key() {
  // @@protoc_insertion_point(field_release:proto.PeerToRelay.public_key)
  
  return public_key_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void PeerToRelay::set_allocated_public_key(::std::string* public_key) {
  if (public_key != NULL) {
    
  } else {
    
  }
  public_key_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), public_key);
  // @@protoc_insertion_point(field_set_allocated:proto.PeerToRelay.public_key)
}

// bytes data = 3;
inline void PeerToRelay::clear_data() {
  data_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& PeerToRelay::data() const {
  // @@protoc_insertion_point(field_get:proto.PeerToRelay.data)
  return data_.GetNoArena();
}
inline void PeerToRelay::set_data(const ::std::string& value) {
  
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:proto.PeerToRelay.data)
}
#if LANG_CXX11
inline void PeerToRelay::set_data(::std::string&& value) {
  
  data_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:proto.PeerToRelay.data)
}
#endif
inline void PeerToRelay::set_data(const char* value) {
  
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:proto.PeerToRelay.data)
}
inline void PeerToRelay::set_data(const void* value, size_t size) {
  
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:proto.PeerToRelay.data)
}
inline ::std::string* PeerToRelay::mutable_data() {
  
  // @@protoc_insertion_point(field_mutable:proto.PeerToRelay.data)
  return data_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* PeerToRelay::release_data() {
  // @@protoc_insertion_point(field_release:proto.PeerToRelay.data)
  
  return data_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void PeerToRelay::set_allocated_data(::std::string* data) {
  if (data != NULL) {
    
  } else {
    
  }
  data_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), data);
  // @@protoc_insertion_point(field_set_allocated:proto.PeerToRelay.data)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)


}  // namespace proto

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_relay_5fpeer_2eproto__INCLUDED
